# Exclude a variety of commonly ignored directories.
exclude = [
    ".pyi",
    "exp_db_populator/passwords"
]

src = ["exp_db_populator"]

# Set the maximum line length to 100.
line-length = 100
indent-width = 4

[lint]
extend-select = [
    "N",  # pep8-naming
    # "D",  # pydocstyle (can use this later but for now causes too many errors)
    "I",  # isort (for imports)
    "E501",  # Line too long ({width} > {limit})
    "E",
    "F",
]
ignore = [
    "D406",  # Section name should end with a newline ("{name}")
    "D407",  # Missing dashed underline after section ("{name}")
]
[lint.per-file-ignores]
"tests/*" = [
    "N802",
    "D100",
    "D101",
    "D102",
    "E501",
    "ANN",
]
"exp_db_populator/cli.py" = [
    "E402"
]

[lint.pydocstyle]
# Use Google-style docstrings.
convention = "google"
